# Generated by Django 5.0 on 2024-01-22 15:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('specialty', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 18, 1, 16, 901034))),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('disease', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=15)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2024, 1, 22, 18, 1, 16, 932283))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
            ],
        ),
    ]
