# Generated by Django 5.0 on 2024-01-22 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_doctor_time_starts_working_doctor_working_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='doctor',
            name='time_ends_working',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 11, 0)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 20, 46, 9, 16091)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 20, 46, 9, 47738)),
        ),
    ]
