# Generated by Django 5.0 on 2024-01-23 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_doctor_working_hours_doctor_time_ends_working_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 14, 11, 10, 82889)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time_ends_working',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 11, 0)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='time_starts_working',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 8, 0)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 14, 11, 10, 129848)),
        ),
    ]
